CREATE TABLE `TB_VEICULOS` (
	`ID_VEICULO` bigint NOT NULL AUTO_INCREMENT,
	`ID_COR` varchar(20) NOT NULL,
	`ID_COMBUSTIVEL` int NOT NULL,
	`ID_MODELO` bigint NOT NULL,
	`PLACA` varchar(8) NOT NULL,
	`CAMBIO` int(2) NOT NULL,
	`KM` int(10) NOT NULL,
	`ANO_FABRICANTE` DATE NOT NULL,
	`ANO_MODELO` DATE NOT NULL,
	`LICENCIADO` BOOLEAN NOT NULL,
	`IPVA` BOOLEAN(2) NOT NULL,
	`DESCRICAO` varchar(255) NOT NULL,
	`FOTO` longblob NOT NULL,
	`VALOR` DECIMAL(30) NOT NULL,
	PRIMARY KEY (`ID_VEICULO`)
);

CREATE TABLE `TB_FABRICANTE` (
	`ID_FABRICANTE` bigint NOT NULL,
	`NOME` varchar(30) NOT NULL AUTO_INCREMENT,
	`ID_MODELO` bigint NOT NULL
);

CREATE TABLE `TB_CLIENTE` (
	`NOME` varchar(30) NOT NULL,
	`E-MAIL` varchar(30) NOT NULL,
	`TELEFONE` varchar(12) NOT NULL,
	`DESCRICAO` varchar(400) NOT NULL
);

CREATE TABLE `TB_MODELO` (
	`ID_MODELO` bigint NOT NULL,
	`NOME` varchar(100) NOT NULL
);

CREATE TABLE `TB_OPCIONAIS` (
	`ID_OPCIONAIS` bigint NOT NULL,
	`NOME_OPCIONAL` varchar(255) NOT NULL,
	PRIMARY KEY (`ID_OPCIONAIS`)
);

CREATE TABLE `TB_COR` (
	`ID_COR` bigint NOT NULL AUTO_INCREMENT,
	`NOME` varchar(30) NOT NULL,
	PRIMARY KEY (`ID_COR`)
);

CREATE TABLE `TB_COMBUSTÍVEL` (
	`ID_COMBUSTIVEL` bigint NOT NULL AUTO_INCREMENT,
	`NOME` varchar(50) NOT NULL,
	PRIMARY KEY (`ID_COMBUSTIVEL`)
);

CREATE TABLE `TB_OPCIONAIS_VEICULOS` (
	`ID_OPCIONAIS_VEICULOS` bigint NOT NULL AUTO_INCREMENT,
	`ID_VEICULO` bigint NOT NULL,
	`ID_OPCIONAL` bigint NOT NULL,
	PRIMARY KEY (`ID_OPCIONAIS_VEICULOS`)
);

ALTER TABLE `TB_VEICULOS` ADD CONSTRAINT `TB_VEICULOS_fk0` FOREIGN KEY (`ID_COR`) REFERENCES `TB_COR`(`ID_COR`);

ALTER TABLE `TB_VEICULOS` ADD CONSTRAINT `TB_VEICULOS_fk1` FOREIGN KEY (`ID_COMBUSTIVEL`) REFERENCES `TB_COMBUSTÍVEL`(`ID_COMBUSTIVEL`);

ALTER TABLE `TB_VEICULOS` ADD CONSTRAINT `TB_VEICULOS_fk2` FOREIGN KEY (`ID_MODELO`) REFERENCES `TB_MODELO`(`ID_MODELO`);

ALTER TABLE `TB_FABRICANTE` ADD CONSTRAINT `TB_FABRICANTE_fk0` FOREIGN KEY (`ID_MODELO`) REFERENCES `TB_MODELO`(`ID_MODELO`);

ALTER TABLE `TB_OPCIONAIS_VEICULOS` ADD CONSTRAINT `TB_OPCIONAIS_VEICULOS_fk0` FOREIGN KEY (`ID_VEICULO`) REFERENCES `TB_VEICULOS`(`ID_VEICULO`);

ALTER TABLE `TB_OPCIONAIS_VEICULOS` ADD CONSTRAINT `TB_OPCIONAIS_VEICULOS_fk1` FOREIGN KEY (`ID_OPCIONAL`) REFERENCES `TB_OPCIONAIS`(`ID_OPCIONAIS`);

